@url = http://localhost:5000

### Bootstrapper Entrypoint
GET {{url}}/

### gRPC Services
GET {{url}}/grpc-endpoints

### Proto Contract Files
GET {{url}}/proto

### List of Enabled Modules
GET {{url}}/modules

### Change Logging Level
POST {{url}}/logging/level?level=information

### Health Checks of Liveness Probes
GET {{url}}/health-checks/live

### Health Checks of Readiness  Probes
GET {{url}}/health-checks/ready

### Sign-Up
POST {{url}}/users-module/users/sign-up
Content-Type: application/json

{
  "email": "user47@email.com",
  "username": "user47",
  "password": "Password123!",
  "role": "user",
  "claims": {
    "permissions": [
      "users"
    ]
  }
}

### Sign-In
# @name sign_in
POST {{url}}/users-module/users/sign-in
Content-Type: application/json

{
    "email": "user47@email.com",
    "password": "Password123!"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

### Get Profile Information
GET {{url}}/users-module/users/me
Authorization: Bearer {{accessToken}}

### Revoke Refresh Token
POST {{url}}/users-module/users/refresh-tokens/revoke
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "bFEUh3uEEvDS11QUM52FOSOIQ4NVrwAbh5szI3b"
}

### Refresh Access Token
POST {{url}}/users-module/users/refresh-tokens/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "bFEUh3uEEvDS11QUM52FOSOIQ4NVrwAbh5szI3b"
}

### Get Users
GET {{url}}/users-module/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}
#X-API-Key: 6CBxzdYcEgNDrRhMbDpkBF7e4d4Kib46dwL9ZE5egiL0iL5Y3dzREUBSUYVUwUkN

### Notifications
GET {{url}}/notifications-module