@url = http://localhost:5187/users-module

###
POST {{url}}/users/sign-up
Content-Type: application/json

{
  "email": "user1@email.com",
  "username": "user1",
  "password": "Password123!",
  "role": "user",
  "claims": {
    "permissions": [
      "users"
    ]
  }
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "user1@edux.com",
    "password": "Password123!"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/users/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users

###
POST {{url}}/users/refresh-tokens/revoke
Content-Type: application/json

{
  "refreshToken": "string"
}

###
POST {{url}}/users/refresh-tokens/use
Content-Type: application/json

{
  "refreshToken": "string"
}
