version: '3.8'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    user: root
    ports:
      - "1433:1433"
    networks:
      - eduxnetwork
    environment:
      SA_PASSWORD: Password123
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver:/var/opt/mssql/data

  mongo:
    container_name: mongo-db
    image: mongo
    restart: unless-stopped
    networks:
      - eduxnetwork
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - eduxnetwork
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  seq:
    image: datalust/seq:2023.4
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:80
    networks:
      - eduxnetwork
    volumes: 
      - seq:/data

  vault:
    image: vault:1.13.3
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    ports:
      - 8200:8200
    networks:
      - eduxnetwork
    volumes:
      - vault:/data
    cap_add:
      - IPC_LOCK

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - eduxnetwork
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - eduxnetwork
    volumes:
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - eduxnetwork
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  edux:
    image: edux:latest
    container_name: edux
    ports:
      - 4000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - eduxnetwork
    depends_on:
      - vault
      - rabbitmq
      - sql-server-db
      - prometheus
      - redis

networks:
  eduxnetwork:
    name: edux-network

volumes:
  sqlserver:
    driver: local
  rabbitmq:
    driver: local
  seq:
    driver: local
  vault:
    driver: local
  redis:
    driver: local
  prometheus:
    driver: local
  grafana:
    driver: local
  mongo:
    driver: local
