version: '3.8'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Password123
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver:/var/opt/mssql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  sqlserver:
    driver: local
  rabbitmq:
    driver: local